# 使用 Node.js 官方镜像作为构建环境
FROM node:22.1.0 as builder

# # 设置工作目录
# WORKDIR /app

# 复制项目文件
COPY ./app-vue/ /

# 清理缓存
RUN npm cache clean --force

# 更换为腾讯源
# RUN npm config set registry https://mirrors.tencent.com/npm/

# 更换为淘宝源
RUN npm config set registry https://registry.npmmirror.com/

# 安装项目依赖
RUN npm install 
RUN npm run build

# 使用 Nginx 来提供静态文件
FROM nginx:stable-alpine

COPY ./docker/nginx/conf.d /etc/nginx/conf.d
RUN  mkdir -p /data/wwwlogs/ && chown -R nobody:nobody /data/wwwlogs/
COPY --from=builder dist dist

RUN mkdir -p /dist/config/dist
COPY --from=builder /dist /dist/config/dist
COPY --from=builder /dist/index.html /dist/config

# 暴露端口
EXPOSE 80

# 启动 Nginx 服务
CMD ["nginx", "-g", "daemon off;"]
